// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_ss_common.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_msg_5fss_5fcommon_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_msg_5fss_5fcommon_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_msg_5fss_5fcommon_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_msg_5fss_5fcommon_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_msg_5fss_5fcommon_2eproto;
namespace SSMessage {
class ServerFirstPackage;
class ServerFirstPackageDefaultTypeInternal;
extern ServerFirstPackageDefaultTypeInternal _ServerFirstPackage_default_instance_;
}  // namespace SSMessage
PROTOBUF_NAMESPACE_OPEN
template<> ::SSMessage::ServerFirstPackage* Arena::CreateMaybeMessage<::SSMessage::ServerFirstPackage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace SSMessage {

// ===================================================================

class ServerFirstPackage :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SSMessage.ServerFirstPackage) */ {
 public:
  ServerFirstPackage();
  virtual ~ServerFirstPackage();

  ServerFirstPackage(const ServerFirstPackage& from);
  ServerFirstPackage(ServerFirstPackage&& from) noexcept
    : ServerFirstPackage() {
    *this = ::std::move(from);
  }

  inline ServerFirstPackage& operator=(const ServerFirstPackage& from) {
    CopyFrom(from);
    return *this;
  }
  inline ServerFirstPackage& operator=(ServerFirstPackage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ServerFirstPackage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ServerFirstPackage* internal_default_instance() {
    return reinterpret_cast<const ServerFirstPackage*>(
               &_ServerFirstPackage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ServerFirstPackage& a, ServerFirstPackage& b) {
    a.Swap(&b);
  }
  inline void Swap(ServerFirstPackage* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ServerFirstPackage* New() const final {
    return CreateMaybeMessage<ServerFirstPackage>(nullptr);
  }

  ServerFirstPackage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ServerFirstPackage>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ServerFirstPackage& from);
  void MergeFrom(const ServerFirstPackage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ServerFirstPackage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SSMessage.ServerFirstPackage";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_msg_5fss_5fcommon_2eproto);
    return ::descriptor_table_msg_5fss_5fcommon_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kExternalIpFieldNumber = 1,
    kExternalPortFieldNumber = 2,
  };
  // bytes external_ip = 1;
  void clear_external_ip();
  const std::string& external_ip() const;
  void set_external_ip(const std::string& value);
  void set_external_ip(std::string&& value);
  void set_external_ip(const char* value);
  void set_external_ip(const void* value, size_t size);
  std::string* mutable_external_ip();
  std::string* release_external_ip();
  void set_allocated_external_ip(std::string* external_ip);
  private:
  const std::string& _internal_external_ip() const;
  void _internal_set_external_ip(const std::string& value);
  std::string* _internal_mutable_external_ip();
  public:

  // int32 external_port = 2;
  void clear_external_port();
  ::PROTOBUF_NAMESPACE_ID::int32 external_port() const;
  void set_external_port(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_external_port() const;
  void _internal_set_external_port(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:SSMessage.ServerFirstPackage)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr external_ip_;
  ::PROTOBUF_NAMESPACE_ID::int32 external_port_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_msg_5fss_5fcommon_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ServerFirstPackage

// bytes external_ip = 1;
inline void ServerFirstPackage::clear_external_ip() {
  external_ip_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& ServerFirstPackage::external_ip() const {
  // @@protoc_insertion_point(field_get:SSMessage.ServerFirstPackage.external_ip)
  return _internal_external_ip();
}
inline void ServerFirstPackage::set_external_ip(const std::string& value) {
  _internal_set_external_ip(value);
  // @@protoc_insertion_point(field_set:SSMessage.ServerFirstPackage.external_ip)
}
inline std::string* ServerFirstPackage::mutable_external_ip() {
  // @@protoc_insertion_point(field_mutable:SSMessage.ServerFirstPackage.external_ip)
  return _internal_mutable_external_ip();
}
inline const std::string& ServerFirstPackage::_internal_external_ip() const {
  return external_ip_.GetNoArena();
}
inline void ServerFirstPackage::_internal_set_external_ip(const std::string& value) {
  
  external_ip_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void ServerFirstPackage::set_external_ip(std::string&& value) {
  
  external_ip_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:SSMessage.ServerFirstPackage.external_ip)
}
inline void ServerFirstPackage::set_external_ip(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  external_ip_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:SSMessage.ServerFirstPackage.external_ip)
}
inline void ServerFirstPackage::set_external_ip(const void* value, size_t size) {
  
  external_ip_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:SSMessage.ServerFirstPackage.external_ip)
}
inline std::string* ServerFirstPackage::_internal_mutable_external_ip() {
  
  return external_ip_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ServerFirstPackage::release_external_ip() {
  // @@protoc_insertion_point(field_release:SSMessage.ServerFirstPackage.external_ip)
  
  return external_ip_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ServerFirstPackage::set_allocated_external_ip(std::string* external_ip) {
  if (external_ip != nullptr) {
    
  } else {
    
  }
  external_ip_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), external_ip);
  // @@protoc_insertion_point(field_set_allocated:SSMessage.ServerFirstPackage.external_ip)
}

// int32 external_port = 2;
inline void ServerFirstPackage::clear_external_port() {
  external_port_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ServerFirstPackage::_internal_external_port() const {
  return external_port_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ServerFirstPackage::external_port() const {
  // @@protoc_insertion_point(field_get:SSMessage.ServerFirstPackage.external_port)
  return _internal_external_port();
}
inline void ServerFirstPackage::_internal_set_external_port(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  external_port_ = value;
}
inline void ServerFirstPackage::set_external_port(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_external_port(value);
  // @@protoc_insertion_point(field_set:SSMessage.ServerFirstPackage.external_port)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace SSMessage

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_msg_5fss_5fcommon_2eproto
